package proviz.asci.old;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * Created by Burak on 1/25/17.
 */
public class trivial6 {
    private JTextField textField1;
    private JComboBox deviceTypeComboBox;
    private JLabel deviceNameLabel;
    private JLabel deviceUniqueId;
    private JLabel deviceTypeLabel;
    private JPanel deviceNamePanel;
    private JPanel deviceUniqueIdPanel;
    private JPanel deviceTypePanel;
    private JPanel componentPanel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        componentPanel = new JPanel();
        componentPanel.setLayout(new GridBagLayout());
        componentPanel.setMaximumSize(new Dimension(-1, 100));
        componentPanel.setPreferredSize(new Dimension(150, 100));
        deviceNamePanel = new JPanel();
        deviceNamePanel.setLayout(new BorderLayout(40, 0));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(20, 20, 0, 20);
        componentPanel.add(deviceNamePanel, gbc);
        deviceNameLabel = new JLabel();
        deviceNameLabel.setText("Device Name:");
        deviceNamePanel.add(deviceNameLabel, BorderLayout.WEST);
        textField1 = new JTextField();
        textField1.setColumns(35);
        deviceNamePanel.add(textField1, BorderLayout.CENTER);
        deviceUniqueIdPanel = new JPanel();
        deviceUniqueIdPanel.setLayout(new BorderLayout(20, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(20, 20, 0, 20);
        componentPanel.add(deviceUniqueIdPanel, gbc);
        deviceUniqueId = new JLabel();
        deviceUniqueId.setText("Device Unique Id:");
        deviceUniqueIdPanel.add(deviceUniqueId, BorderLayout.WEST);
        final JLabel label1 = new JLabel();
        label1.setText("Label");
        deviceUniqueIdPanel.add(label1, BorderLayout.CENTER);
        deviceTypePanel = new JPanel();
        deviceTypePanel.setLayout(new BorderLayout(40, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(20, 20, 0, 20);
        componentPanel.add(deviceTypePanel, gbc);
        deviceTypeLabel = new JLabel();
        deviceTypeLabel.setText("Device Type:");
        deviceTypePanel.add(deviceTypeLabel, BorderLayout.WEST);
        deviceTypeComboBox = new JComboBox();
        deviceTypeComboBox.setAlignmentX(0.0f);
        deviceTypeComboBox.setAlignmentY(0.0f);
        deviceTypePanel.add(deviceTypeComboBox, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return componentPanel;
    }
}
