package proviz.asci.old;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * Created by Burak on 1/23/17.
 */
public class trivial {

    private JRadioButton wifiRadioBox;
    private JRadioButton bluetoothRadioBox;
    private JRadioButton usbRadioBox;
    private JLabel bluetoothLogo;
    private JLabel usbLogo;
    private JLabel wifiLogo;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel2, BorderLayout.CENTER);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        panel2.add(panel3);
        bluetoothLogo = new JLabel();
        bluetoothLogo.setIcon(new ImageIcon(getClass().getResource("/images/connection_type_bluetooth.png")));
        bluetoothLogo.setText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel3.add(bluetoothLogo, gbc);
        bluetoothRadioBox = new JRadioButton();
        bluetoothRadioBox.setHorizontalTextPosition(11);
        bluetoothRadioBox.setLabel("");
        bluetoothRadioBox.setText("");
        bluetoothRadioBox.setVerticalAlignment(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel3.add(bluetoothRadioBox, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        panel2.add(panel4);
        usbLogo = new JLabel();
        usbLogo.setIcon(new ImageIcon(getClass().getResource("/images/connection_type_usb.png")));
        usbLogo.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel4.add(usbLogo, gbc);
        usbRadioBox = new JRadioButton();
        usbRadioBox.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        panel4.add(usbRadioBox, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridBagLayout());
        panel2.add(panel5);
        wifiLogo = new JLabel();
        wifiLogo.setIcon(new ImageIcon(getClass().getResource("/images/connection_type_wifi.png")));
        wifiLogo.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel5.add(wifiLogo, gbc);
        wifiRadioBox = new JRadioButton();
        wifiRadioBox.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        panel5.add(wifiRadioBox, gbc);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(bluetoothRadioBox);
        buttonGroup.add(usbRadioBox);
        buttonGroup.add(wifiRadioBox);
    }
}
